version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: alarm_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-web
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

  api:
    build: ./alarm-care-pro-api-python
    container_name: alarm-care-pro-api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/alarm_app
      - SECRET_KEY=your-secret-key-change-this-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DEBUG=True
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./alarm-care-pro-api-python/app:/app/app
    command: >
      sh -c "
        sleep 15 &&
        echo 'Waiting for PostgreSQL...' &&
        until pg_isready -h postgres -p 5432 -U admin; do
          sleep 1
        done &&
        echo 'PostgreSQL is ready!' &&
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    restart: unless-stopped

volumes:
  postgres_data:
